### ISSUE TITLE
vendor bundle builds before app bundle

### ISSUE THREAD

**Issue by bflannery** [survivejs/webpack-book#286]
I'm following the book by chapter and referencing this repo to compare my webpack config. I keep noticing that the book build always has the app first, followed by the image files, then the vendor bundle. When I run my build the vendor bundle is always first with the app build coming after the image files. Is this problematic? It would seem that the `parts.extractBundles` is placing the vendor bundle ahead in the entry path.

My bundle builds and the config / package.json are the same as this repo but will post photos if needed to review.

**Comment by bebraw** [comment]
Can you push your code to a GitHub repository? I can have a good look.

This could be expected behavior but it's a good idea to check.

**Comment by bflannery** [comment]
Sure! https://github.com/bflannery/Survive-Js-Demo.

Also getting this error at the bottom of the build. 

```
Worker error Error: No code sections found
    at Bundle.validate (/Users/brianflannery/Development/webpack-demo/node_modules/inspectpack/lib/models/bundle.js:54:11)
    at createBundle (/Users/brianflannery/Development/webpack-demo/node_modules/inspectpack/lib/models/bundle.js:262:12)
    at Immediate.setImmediate [as _onImmediate] (/Users/brianflannery/Development/webpack-demo/node_modules/inspectpack/lib/models/bundle.js:313:7)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
Worker error Error: No code sections found
    at Bundle.validate (/Users/brianflannery/Development/webpack-demo/node_modules/inspectpack/lib/models/bundle.js:54:11)
    at createBundle (/Users/brianflannery/Development/webpack-demo/node_modules/inspectpack/lib/models/bundle.js:262:12)
    at Immediate.setImmediate [as _onImmediate] (/Users/brianflannery/Development/webpack-demo/node_modules/inspectpack/lib/models/bundle.js:313:7)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
Worker error Error: No code sections found
    at Bundle.validate (/Users/brianflannery/Development/webpack-demo/node_modules/inspectpack/lib/models/bundle.js:54:11)
    at createBundle (/Users/brianflannery/Development/webpack-demo/node_modules/inspectpack/lib/models/bundle.js:262:12)
    at Immediate.setImmediate [as _onImmediate] (/Users/brianflannery/Development/webpack-demo/node_modules/inspectpack/lib/models/bundle.js:313:7)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
````

**Comment by bebraw** [comment]
Hi,

I solved the issue by moving `plugins: [new DashboardPlugin()],` to `developmentConfig`. Note that you had `"build:lib": "webpack --config webpack.lib.js",`. I had to remove the trailing comma as standard JSON doesn't support them.

I understand the order now too. It's that `manifest.<something>.js` file that bootstraps the whole application and it loaded just fine for me.

Sorry for the late reply. Busy days.

**Comment by bflannery** [comment]
🙌🙌🙌 that worked! I'll have to research that plugin and see why that was causing that error. I realized after I pushed the code that the trailing comma was causing a build issue as well. 

Everything is working great now, thanks for the response and look forward to reading more from you guys!

**Comment by bebraw** [comment]
Cool to hear. 👍 

See [the new maintenance book](https://survivejs.com/maintenance/). Feedback on that would be valuable.

**Comment by davidhallj** [comment]
I had the same issue with the same error message. Removing the DashboardPlugin fixed it for me. 

The issue actually only started presenting itself when I combined the CopyWebpackPlugin with the DashboardPlugin.
